apiVersion: v1
kind: ReplicationController
metadata:
 name: mysql-01
spec:
 replicas: 1
 selector:
  app: mysql-01 
 template:
  metadata:
   labels:
    app: mysql-01
  spec:
   containers:
   - name: mysql-01-wordpress
     image: mysql
     ports:
     - containerPort: 3306
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: wordpress
     - name: MYSQL_DATABASE
       value: wordpress
     - name: MYSQL_USER
       value: wordpress
     - name: MYSQL_PASSWORD
       value: wordpress
---
apiVersion: v1
kind: Service
metadata:
 name: mysql-01-svc
spec:
 selector: 
  app: mysql-01
 ports:
 - port: 3306 