apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-01
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: wordpress-01
  spec:
   containers:
   - name: wordpress-01-demo
     image: wordpress
     ports:
     - containerPort: 80
     envFrom:
      - configMapRef:
          name:  wordpress-01-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-01-svc
  labels:
    app: wordpress-01
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32765
  selector:
    app: wordpress-01
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: wordpress-01-configmap
data:
  wordpress_01_dbname: wordpress
  wordpress_01_dbuser: wordpress
  wordpress_01_dbpass: wordpress
  wordpress_01_dbhost: mysql-01-svc